# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      matrix:
        arch: ["aarch64", "x86_64"]
        libc: ["gnu", "musl"]
    runs-on: ubuntu-24.04${{ matrix.arch == 'aarch64' && '-arm' || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
      - name: Run tests
        shell: bash
        run: cargo test --target=${{ matrix.arch }}-unknown-linux-${{ matrix.libc }} -- --test-threads=1

  deps:
    name: unused dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: Swatinem/rust-cache@v2
    - name: Check unused dependencies
      uses: bnjbvr/cargo-machete@v0.7.0

  spelling:
    name: spell check with typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Spell Check Repo
      uses: crate-ci/typos@master
